### ISSUE TITLE
Product property(isMicrosoftProduct)

### ISSUE THREAD

**Issue by papasam** [MicrosoftDocs/partner-center-sdk.zh-tw#1]
"Indicates whether this is a Microswoft product."
Is it really you have a Microswoft product or it's just a type error? Thanks.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: b1f14f8b-518b-8bfa-3d3d-9e533a204945
* Version Independent ID: 6fb31e13-f775-187b-0456-97b4e38f80e3
* Content: [產品資源 - Partner Center app developer](https://docs.microsoft.com/zh-tw/partner-center/develop/product-resources#feedback)
* Content Source: [develop/product-resources.md](https://github.com/MicrosoftDocs/partner-center-sdk.zh-tw/blob/live/develop/product-resources.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by srvbpigh** [comment]
Hello, @papasam
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonWHowell** [comment]
This issue is resolved in the English version. Thanks! Jason
